### ISSUE TITLE
项目中NT.Tools是引用的哪个类啊？现在运行项目报错了

### ISSUE THREAD

**Issue by jibp** [NiTian1207/Music-Downloader-UI#2]
![image](https://user-images.githubusercontent.com/6679245/100688148-97e27100-33bc-11eb-8d14-143138a32602.png)

**Comment by NiTian1207** [comment]
是我的另一个仓库
https://github.com/NiTian1207/NT.Tools

**Comment by jibp** [comment]
> 是我的另一个仓库
> https://github.com/NiTian1207/NT.Tools

好的，谢谢 ，你做的这个demo很棒

**Comment by jibp** [comment]
![image](https://user-images.githubusercontent.com/6679245/100692506-f829e080-33c5-11eb-8534-19aa372eafeb.png)
这边的代码是不是没全部提交啊？缺少对象

**Comment by jibp** [comment]
![image](https://user-images.githubusercontent.com/6679245/100692855-a9c91180-33c6-11eb-9b5a-c71f605cd905.png)
这个类能给下不？谢谢

**Comment by NiTian1207** [comment]
我重新推送了一遍，你再试试
