### ISSUE TITLE
我分别搜索了4个歌手并下载全部歌曲，可能超过200甚至更多的首歌曲就报错闪退，以下是错误日志

### ISSUE THREAD

**Issue by a512154224** [NiTian1207/Music-Downloader-UI#7]
--- 2021-01-13 09:02:05 ---
System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 MusicDownloader.DownloadPage.UpdateList()
   在 MusicDownloader.Library.Music.DownloadProgressUpdate(Object sender, DownloadProgressChangedEventArgs e)
   在 System.Net.WebClient.OnDownloadProgressChanged(DownloadProgressChangedEventArgs e)
   在 System.Net.WebClient.ReportDownloadProgressChanged(Object arg)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
--- 2021-01-13 09:02:06 ---
System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 MusicDownloader.DownloadPage.UpdateList()
   在 MusicDownloader.Library.Music.DownloadProgressUpdate(Object sender, DownloadProgressChangedEventArgs e)
   在 System.Net.WebClient.OnDownloadProgressChanged(DownloadProgressChangedEventArgs e)
   在 System.Net.WebClient.ReportDownloadProgressChanged(Object arg)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by NiTian1207** [comment]
感谢反馈，正在处理
