### ISSUE TITLE
本地api初始化的功能似乎还有bug

### ISSUE THREAD

**Issue by tumuyan** [NiTian1207/Music-Downloader-UI#8]
一开始初始化失败的。我删除AppData\Roaming\MusicDownloader内的全部文件，并重新打开软件，等待较长的时间，初始化成功了，测试API功能也正常。
看到仍然有error log，故上传log供参考。

[INSTALL2.txt](https://github.com/NiTian1207/Music-Downloader-UI/files/5809903/INSTALL2.txt)
[normal.log](https://github.com/NiTian1207/Music-Downloader-UI/files/5809904/normal.log)
[Api.txt](https://github.com/NiTian1207/Music-Downloader-UI/files/5809905/Api.txt)
[INSTALL1.txt](https://github.com/NiTian1207/Music-Downloader-UI/files/5809907/INSTALL1.txt)
[error.log](https://github.com/NiTian1207/Music-Downloader-UI/files/5809906/error.log)

**Comment by NiTian1207** [comment]
这个error.log存的是npm输出的错误信息，没啥用的😂
