### ISSUE TITLE
输入内容后回车载入音乐列表

### ISSUE THREAD

**Issue by tumuyan** [NiTian1207/Music-Downloader-UI#9]
我习惯输入内容后，按回车完成操作。  
在这个软件的搜索框中，这样的功能是正常的。但是当输入歌单或者专辑时，按回车没有反应，必须点输入框边上的按钮。
我测试了一下，取消这段函数的注释后，就能够按回车时载入歌单。但是为什么原先把这里注释掉了？

https://github.com/NiTian1207/Music-Downloader-UI/blob/7b6b49f1ccea4f3f4d701db3c2acd8d18dd464aa/Music-Downloader-UI/Pages/SearchPage.xaml.cs#L290

**Comment by NiTian1207** [comment]
我记不清了,可能是注释多了😂
